name: test and deploy the app
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: git the code
        uses: actions/checkout@v3
      - name: install node js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: install packages
        run: npm ci
      - name: run lint 
        run: npm run lint
      - name: run unit tests
        run: npm run test
      - name: build the app
        run: npm run build
      - name: deploy the app
        run: echo "application deployed"